version: "3.8"
services:
  app:
    build: .
    container_name: food-ordering-application
    image: ${DOCKER_IMAGE:-food-ordering-application-server:v0.0.1}
    restart: always
    ports:
      - "8081:8080"
    networks:
      - food-ordering-application_common-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/food_ordering_application?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pasindu123
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: mysql:8.0
#    platform: linux/amd64
    container_name: mysqldb
    restart: always
    networks:
      - food-ordering-application_common-net
    environment:
        MYSQL_ROOT_PASSWORD: pasindu123
        MYSQL_DATABASE: food_ordering_application
        MYSQL_USER: pasindu
        MYSQL_PASSWORD: pasindu123
        MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data:

networks:
  food-ordering-application_common-net:
