[sbx]
# Sandbox Server IPs
# example: 54.1.1.1 ansible_user=ubuntu

[qa]
# QA Server IPs
# example: 54.2.2.2 ansible_user=ubuntu

[stg]
# Staging Server IPs
# example: 54.3.3.3 ansible_user=ubuntu

[prod]
# Production Server IPs
# example: 54.4.4.4 ansible_user=ubuntu
